krisnails/django_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

krisnails/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls')),


]
#if settings.DEBUG:
#    import debug_toolbar
#
#    urlpatterns = [
#                      path('__debug__/', include(debug_toolbar.urls)),
#                  ] + urlpatterns
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from django.conf import settings
from django.views.decorators.cache import cache_page

from services import views

app_name = 'services'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('service/', views.Services.as_view(), name='service'),
    path('portfolio/', views.Portfolio.as_view(), name='portfolio'),
    path('contact/', views.show_contacts_and_send_message, name='contact'),
    path('about/', views.About.as_view(), name='about'),
    path('blog/', views.Blog.as_view(), name='blog'),
    path('blog/<str:slug>', views.ShowPost.as_view(), name='show_post'),
    path('contact_form/', views.send_message, name='contact_form'),
]

templates/inc/_contact_form.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% else %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

 <section class="akame-contact-area bg-gray section-padding-80">
        <div class="container">
            <div class="row">
                <!-- Section Heading -->
                <div class="col-12">
                    <div class="section-heading text-center">
                        <h2>Оставьте свое сообщение</h2>
                        <p>Я свяжусь с вами при первой возможности.</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <!-- Form -->

                    <form action="{% url 'services:contact' %}" method="POST" class="akame-contact-form border-0 p-0">
                        {% csrf_token %}
                        {{ form.non_field.errors }}
                        <div class="row">
                            <div class="col-lg-6">
                                <input type="text" name="name" class="form-control mb-30" placeholder="Ваше имя">
                            </div>
                            <div class="col-lg-6">
                                <input type="tel" name="telephone" class="form-control mb-30" placeholder="Ваш номер телефона">
                            </div>
                            <div class="col-12">
                                <input type="email" name="email" class="form-control mb-30" placeholder="Ваш E-mail">
                            </div>
{#                            <div class="col-12">#}
{#                                <input type="date"  name="email" class="form-control mb-30" placeholder="MM/DD/YYYY" onfocus="(this.type='date')">#}
{#                            </div>#}
                            <div class="col-12">
                                <textarea name="content" required class="form-control mb-30" placeholder="Ваше сообщение..."></textarea>
                            </div>
                            <div class="col-12 text-center">
                                <button type="submit" class="btn akame-btn btn-3 mt-15 active">Отправить сообщение</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

templates/inc/_nav.html
<!-- NAVBAR Start -->
    <header class="header-area">
        <!-- Top NAVBAR Area Start -->
        <div class="top-header-area">
            <div class="container h-100">
                <div class="row h-100 align-items-center">
                    <div class="col-5">
                        <div class="top-header-content">
                            <p>Добро пожаловать!</p>
                        </div>
                    </div>
                    <div class="col-7">
                        <div class="top-header-content text-right">
                            <p><i class="fas fa-female" aria-hidden="true"></i> Ваш мастер по уходу за руками — Кристина <span class="mx-2"></span> | <span class="mx-2"></span> <i class="fa fa-mobile" aria-hidden="true"></i> Позвонить мне: 093-339-88-18</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Top NAVBAR Area End -->

        <!-- Main NAVBAR Start -->
        <div class="main-header-area">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Classy Menu -->
                    <nav class="classy-navbar justify-content-between" id="akameNav">

                        <!-- Logo -->
                        <a class="nav-brand" href="{% url 'services:home' %}"><img src="" alt="">KRISNAILS</a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">
                            <!-- Menu Close Button -->
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>
                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul id="nav">
                                    <li class=""><a href="{% url 'services:home' %}">Главная</a></li>
                                   <!-- <li><a href="#">Pages</a>
                                        <ul class="dropdown">
                                            <li><a href="./index.html">- Home</a></li>
                                            <li><a href="./about.html">- About Us</a></li>
                                            <li><a href="./service.html">- Services</a></li>
                                            <li><a href="./portfolio.html">- Portfolio</a></li>
                                            <li><a href="./blog.html">- Blog</a></li>
                                            <li><a href="./single-blog.html">- Blog Details</a></li>
                                            <li><a href="./contact.html">- Contact</a></li>
                                            <li><a href="#">- Dropdown</a>
                                                <ul class="dropdown">
                                                    <li><a href="#">- Dropdown Item</a></li>
                                                    <li><a href="#">- Dropdown Item</a></li>
                                                    <li><a href="#">- Dropdown Item</a></li>
                                                    <li><a href="#">- Dropdown Item</a></li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </li> -->
                                    <li><a href="{% url 'services:portfolio' %}">Портфолио</a></li>
                                    {% if request.user.is_superuser %}
                                    <li><a href="/admin"  target="_blank">Панель администратора</a></li>
                                    {% endif %}
                                    <li><a href="{% url 'services:service' %}">Услуги</a></li>
                                    <li><a href="{% url 'services:about' %}">Обо мне</a></li>
                                    <li><a href="{% url 'services:blog' %}">Блог</a></li>
                                    <li><a href="{% url 'services:contact' %}">Контакты</a></li>
                                </ul>

                                <!-- Cart Icon
                                <div class="cart-icon ml-5 mt-4 mt-lg-0">
                                    <a href="#"><i class="icon_cart"></i></a>
                                </div> -->

                                <!-- Book Icon -->
                                <div class="book-now-btn ml-5 mt-4 mt-lg-0 ml-md-4">
                                    <a href="{% url 'services:contact_form' %}" class="btn akame-btn">Стать счастливее</a>
                                </div>
                            </div>
                            <!-- Nav End -->
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- NAVBAR End -->

templates/inc/_portfolio.html
 <!-- Portfolio Area Start -->
    <section class="akame-portfolio section-padding-0-80 clearfix">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="portfolio-menu text-center mb-50">
                        <button class="btn active" data-filter="*">Все фото</button>
                        {% for tag in tags %}
                            <button class="btn" data-filter=".{{ tag.title }}">{{ tag.title }}</button>
                        {% endfor %}
                        <!--   <button class="btn" data-filter=".coloring">Coloring</button>
                         <button class="btn" data-filter=".barber">Barber</button>
                         <button class="btn" data-filter=".shaving">Shaving</button>
                         <button class="btn" data-filter=".hairstyle">Hairstyle</button>
                         <button class="btn" data-filter=".massage">Massages</button>-->
                    </div>
                </div>
            </div>

            <div class="row akame-portfolio-area">
                {% for item in visit_list %}

                    <!-- Single Portfolio Item -->
                    <div class="col-12 col-sm-6 col-lg-4 akame-portfolio-item nails mb-30 wow fadeInUp
                    {% for tag in item.tags.all %}
                        {{ tag }}
                    {% endfor %}"
                         data-wow-delay="200ms">
                        <div class="akame-portfolio-single-item">
                            <img src="{{ item.photo_after.url }}" alt="">

                            <!-- Overlay Content
                            <div class="overlay-content d-flex align-items-center justify-content-center">
                                <div class="overlay-text text-center">
                                    <h4>Hairstyle</h4>
                                    <p>Consectetur adipisicing elit sed doe</p>
                                </div>
                            </div>-->

                            <!-- Thumbnail Zoom -->
                            <a href="{{ item.photo_after.url }}" class="thumbnail-zoom"><i class="icon_zoom-in_alt"></i></a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Portfolio Area End -->